### Create User
POST http://localhost:3000/users
Content-Type: application/json 

{
    "email": "teste@email.com",
    "name": "teste",
    "admin": true
}

### Get All Users 
GET  http://localhost:3000/users

### Get User by Id
GET http://localhost:3000/users/45

### Edit User
PATCH   http://localhost:3000/users/42
Content-Type: application/json 

{
    "email": "modificação@email.com",
    "name": "modificação",
    "admin": false
}

### Delete User
DELETE http://localhost:3000/users/49

### Get All Posts 
GET http://localhost:3000/posts

### Get Post By Id
GET http://localhost:3000/posts/4

### Create Post
POST http://localhost:3000/posts
Content-Type: application/json 

{
    "title": "teste",
    "content": "teste",
    "authorEmail": "teste@email.com"
}

### Edit Post
PATCH http://localhost:3000/posts/5
Content-Type: application/json 

{
    # "title": "teste",
    # "content": "modificado",
    "authorEmail": "teste@email.com"
}

### Delete Post
DELETE http://localhost:3000/posts/5